@startuml

class Member {
  id: Long
  --
  team: Team
  name: String
}

class Team {
  id: Long
  --
  name: String
  members: List<Member>
}

Member "*" --d-> "team" Team
Team "1 " .u.> "members" Member

@enduml