@startuml

class Member {
  id: Long
  --
  seat: Seat
  name: String
}

class Seat {
  id: Long
  --
  seatNumber: String
  member: Member
}

Member --r--> "seat" Seat
Seat ..r..> "member" Member

@enduml