@startuml

entity product {
  id
  --
  name
  price
}

entity song {
  id
  --
  singer
  writer
}

entity movie {
  id
  --
  director
  actor
}

entity book {
  id
  --
  author
  isbn
}

product -d- song
product -d- movie
product -d- book

@enduml